name: grad_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  supabase_flutter: ^2.9.0
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  avatar_glow: ^3.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  skeletonizer: ^1.4.3
  flutter_spinkit: ^5.2.1
  fl_chart: ^1.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_logo.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
